name: SplitFedLLM

server:
  global-round: 10        
  clients:
    - 1
    - 1
  cut-layers: 4
  model-name: GPT2           # GPT2 / Llama / Bert
  data-name: E2E             # E2E / EMOTION / AG_NEWS / GSM8K
  pretrained_path: GPT2.pt
  model:
    GPT2:
      n_block: 12
    Llama:
      n_block: 12
    Bert:
      n_block: 12
  parameters:
    load: True
    save: True
  validation: False         
  data-distribution:
    non-iid: False
    num-sample: 10000
    num-label: 1
    dirichlet:
      alpha: 1
    refresh-each-round: True
  random-seed: 42

rabbit:
  address: 127.0.0.1
  username: admin
  password: admin
  virtual-host: /

log_path: .
debug_mode: False          

learning:
  learning-rate: 0.00005
  weight-decay: 0.01
  batch-size: 8             
  control-count: 2         
  clip-grad-norm: 1.0

fine-tune:
  enable: True
  name: LoRA
  LoRA:
    r: 8
    alpha: 16
  QLoRA:
    r: 8
    alpha: 16
    bits: 4
    double_quant: True

optimization:
  flash_attention: False    
  precision: fp32
  quantize_hidden: False     
  gradient_checkpointing: True